name: Scrape Properties Daily

on:
  schedule:
    - cron: '0 8 * * *'  # Todos los días a las 8:00 UTC (~5 AM Buenos Aires)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python actionscraping.py

      - name: Commit cambios si los hay
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/data/propiedades.json
          git diff --quiet && git diff --staged --quiet || git commit -m "🔄 Auto-update propiedades.json"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push